M48
; DRILL file {KiCad 8.0.0} date 2024-04-17T20:02:38+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-17T20:02:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C3.000
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T3C6.000
%
G90
G05
T2
X130.45Y-36.0
X130.45Y-158.5
T3
X133.16Y-53.25
X133.325Y-141.25
T1
G00X133.16Y-62.25
M15
G01X133.16Y-132.25
M16
G05
M30
